"use strict";
const producciones = [
    {name: 'Produccion', produccion: '<Programa>',                     produce: ['<Sentencia>', 'PUNTOYCOMA', '<ProgramaFin>']},
    {name: 'Produccion', produccion: '<ProgramaFin>',                  produce: ['<Sentencia>', 'PUNTOYCOMA', '<Programa>']},
    {name: 'Produccion', produccion: '<ProgramaFin>',                  produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<Programa>',                     produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Asignacion>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Ciclo>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Condicional>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Escritura>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Lectura>']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['ID', 'OPERADORASIGNACION', '<Expresion>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<ExpresionLista>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['ID', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['NUMERO', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['FIRST', 'PARENTESIS_OPEN', '<ListaInterna>', 'PARENTESIS_CLOSE', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['PARENTESIS_OPEN','<ExpresionAritmetica>', 'PARENTESIS_CLOSE', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['OPERADOR', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['<Lista>']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['REST', 'PARENTESIS_OPEN', '<ExpresionLista>', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['CONS', 'PARENTESIS_OPEN', '<ExpresionCons>', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionCons>',                produce: ['NUMERO', 'COMA', '<ExpresionLista>']},
    {name: 'Produccion', produccion: '<ExpresionCons>',                produce: ['ID', 'COMA', '<ExpresionLista>']},
    {name: 'Produccion', produccion: '<Lista>',                        produce: ['CORCHETE_OPEN', '<ListaInterna>', 'CORCHETE_CLOSE']},
    {name: 'Produccion', produccion: '<Lista>',                        produce: ['ID']},
    {name: 'Produccion', produccion: '<ListaInterna>',                 produce: ['NUMERO', '<ListaInternaNumero>']},
    {name: 'Produccion', produccion: '<ListaInterna>',                 produce: ['ID', '<ListaInternaNumero>']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['COMA', '<ListaInterna>']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['NUMERO']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['ID']},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['WHILE','PARENTESIS_OPEN', '<Condicion>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Condicion>',                    produce: ['<ExpresionAritmetica>', 'SIGNO', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<Condicional>',                  produce: ['IF','PARENTESIS_OPEN', '<Condicion>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', '<CierreCondicion>']},
    {name: 'Produccion', produccion: '<CierreCondicion>',              produce: ['LLAVE_CLOSE', 'ELSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<CierreCondicion>',              produce: ['LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Escritura>',                    produce: ['<EscribirNumero>']},
    {name: 'Produccion', produccion: '<Escritura>',                    produce: ['<EscribirLista>']},
    {name: 'Produccion', produccion: '<Lectura>',                      produce: ['<LecturaNumero>']},
    {name: 'Produccion', produccion: '<Lectura>',                      produce: ['<LecturaLista>']},
    {name: 'Produccion', produccion: '<EscribirNumero>',               produce: ['WRITEINT', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<EscribirLista>',                produce: ['WRITELIST', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<LecturaNumero>',                produce: ['READINT', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<LecturaLista>',                 produce: ['READLIST', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<EscrituraLectura>',             produce: ['PARENTESIS_OPEN', '<Cadena>', 'COMA', 'ID', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<EscrituraLectura>',             produce: ['PARENTESIS_OPEN', 'ID', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<Cadena>',                       produce: ['COMILLA', 'TEXTO', 'COMILLA']},
];

module.exports = producciones;